name: SpawnEggRecipe
version: 1.0
main: evan.spawneggrecipe.SpawnEggRecipe
api-version: 1.21

commands:
  eggrecipe:
    description: Shows custom spawn egg recipes
    usage: /eggrecipe <mob>